#+STARTUP: showeverything
#+title: R Notes for Professionals

* Chapter 25: Bar Chart

  The purpose of the bar plot is to display the frequencies (or proportions) of
  levels of a factor variable. For example, a bar plot is used to pictorially
  display the frequencies (or proportions) of individuals in various
  socio-economic (factor) groups(levels-high, middle, low). Such a plot will
  help to provide a visual comparison among the various factor levels.

** Section 25.1: barplot() function

   In barplot, factor-levels are placed on the x-axis and frequencies (or
   proportions) of various factor-levels are considered on the y-axis. For each
   factor-level one bar of uniform width with heights being proportional to
   factor level frequency (or proportion) is constructed.

   The ~barplot()~ function is in the graphics package of the R's System
   Library. The ~barplot()~ function must be supplied at least one argument. The
   R help calls this as heights, which must be either vector or a matrix. If it
   is vector, its members are the various factor-levels.

   To illustrate ~barplot()~, consider the following data preparation:

#+begin_src R
  > grades<-c("A+","A-","B+","B","C")
  > Marks<-sample(grades,40,replace=T,prob=c(.2,.3,.25,.15,.1))
  > Marks
  [1] "A+" "A-" "B+" "A-" "A+" "B" "A+" "B+" "A-" "B" "A+" "A-"
  [13] "A-" "B+" "A-" "A-" "A-" "A-" "A+" "A-" "A+" "A+" "C" "C"
  [25] "B" "C" "B+" "C" "B+" "B+" "B+" "A+" "B+" "A-" "A+" "A-"
  [37] "A-" "B" "C" "A+"
#+end_src

   A bar chart of the Marks vector is obtained from

#+begin_src R
  > barplot(table(Marks),main="Mid-Marks in Algorithms")
#+end_src

<pic>

   Notice that, the ~barplot()~ function places the factor levels on the x-axis
   in the lexicographical ~order~ of the levels. Using the parameter
   ~names.arg~, the bars in plot can be placed in the order as stated in the
   vector, grades.

#+begin_src R
  # plot to the desired horizontal axis labels
  > barplot(table(Marks),names.arg=grades ,main="Mid-Marks in Algorithms")
#+end_src

<pic>

   Colored bars can be drawn using the ~col=~ parameter.

#+begin_src R
  > barplot(table(Marks),names.arg=grades,col = c("lightblue", "lightcyan", "lavender", "mistyrose", "cornsilk"), main="Mid-Marks in Algorithms")
#+end_src

<pic>

   A bar chart with horizontal bars can be obtained as follows:

#+begin_src R
  > barplot(table(Marks),names.arg=grades,horiz=TRUE,col = c("lightblue", "lightcyan", "lavender", "mistyrose", "cornsilk"),main="Mid-Marks in Algorithms")
#+end_src

   A bar chart with proportions on the y-axis can be obtained as follows:

#+begin_src R
> barplot(prop.table(table(Marks)),names.arg=grades,col = c("lightblue", "lightcyan", "lavender", "mistyrose", "cornsilk"), main="Mid-Marks in Algorithms")
#+end_src






