#+STARTUP: showeverything
#+title: Linux Notes for Professionals

* Chapter 20: Package Managers

** Section 20.1: How to update packages with the apt package manager

   The Advanced Package Tool, aptly named the 'apt' package manager can handle
   the installation and removal of software on the Debian, Slackware, and other
   Linux Distributions. Below are some simple examples of use:

*** update

    This option retrieves and scans the Packages.gz ﬁles, so that information
    about new and updated packages is available. To do so, enter the following
    command:

#+begin_src bash
  sudo apt-get update
#+end_src

*** upgrade

    This option is used to install the newest versions of all packages currently
    installed on the system. Packages currently installed with new versions
    available are retrieved and upgraded; under no circumstances are currently
    installed packages removed, or packages not already installed retrieved and
    installed. To upgrade, enter the following command:

#+begin_src bash
  sudo apt-get upgrade
#+end_src

*** dist-upgrade

    In addition to performing the function of upgrade, dist-upgrade also
    intelligently handles changing dependencies with new versions of packages.
    It will attempt to upgrade the most important packages at the expense of
    less important ones if necessary. To do so, enter the following command:

#+begin_src bash
  sudo apt-get dist-upgrade
#+end_src

** Section 20.2: How to install a package with the pacman package manager

   In order to search for packages in the databse, searching both in packages'
   names and descriptions:

#+begin_src bash
  pacman -Ss string1 string2 ...
#+end_src

   To install a single package or list of packages (including dependencies),
   issue the following command:

#+begin_src bash
  sudo pacman -S package_name1 package_name2 ...
#+end_src

** Section 20.3: How to update packages with the pacman package manager

   To update a speciﬁc program:

#+begin_src bash
  sudo pacman -S <programName>
#+end_src

    To update entire the system:

#+begin_src bash
  sudo pacman -Syu
#+end_src

** Section 20.4: How to update packages with yum

   Yellowdog Updater, Modiﬁed, one of the last remaining vestiges of Yellow Dog
   Linux, is the package manager used by Red Hat, Fedora, and CentOS systems and
   their derivatives. It can handle the installation and removal of software
   packaged as rpms for these Linux distributions. Below are some simple
   examples of use:

*** search

    This command will attempt to locate software packages in the conﬁgured
    software repositories that match the given search criteria, and display the
    name / version / repository location of the matches it ﬁnds. To use it,
    enter the following command:

#+begin_src bash
  yum search <queryString>
#+end_src

*** install

    This command will attempt to locate and install the named software from the
    conﬁgured software repositories, recursively locating and installing any
    needed prerequisite software as well. To use it, enter the following
    command:

#+begin_src bash
  sudo yum install <packageName>
#+end_src

*** update

    This option is used to install the newest versions of all packages currently
    installed on the system. Packages currently installed with new versions
    available are retrieved and upgraded; new prerequisites are also retrieved
    and installed as necessary, and replaced or obsoleted packages are removed.
    To upgrade, enter the following command:

#+begin_src bash
  sudo yum update
#+end_src

    Unlike apt, most yum commands will also automatically check for updates to
    repository metadata if a check has not been done recently (or if forced to
    do so) and will retrieve and scan updated metadata so that information about
    new and updated packages is available before the requested operation is
    performed.
