#+STARTUP: showeverything
#+title: Python Notes for Professionals

* Chapter 1: Getting started with Python Language

** Section 1.1: Getting Started

   Python is a widely used high-level programming language for general-purpose
   programming, created by Guido van Rossum and ﬁrst released in 1991. Python
   features a dynamic type system and automatic memory management and supports
   multiple programming paradigms, including object-oriented, imperative,
   functional programming, and procedural styles. It has a large and
   comprehensive standard library.

   Two major versions of Python are currently in active use:

   * Python 3.x is the current version and is under active development.

   * Python 2.x is the legacy version and will receive only security updates
     until 2020. No new features will be implemented. Note that many projects
     still use Python 2, although migrating to Python 3 is getting easier.

   You can download and install either version of Python. See Python 3 vs.
   Python 2 for a comparison between them. In addition, some third-parties oﬀer
   re-packaged versions of Python that add commonly used libraries and other
   features to ease setup for common use cases, such as math, data analysis or
   scientiﬁc use. See the list at the [[https://www.python.org/download/alternatives/][official site]].

*** Verify if Python is installed

    To conﬁrm that Python was installed correctly, you can verify that by
    running the following command in your favorite terminal (If you are using
    Windows OS, you need to add path of python to the environment variable
    before using it in command prompt):

#+begin_src bash
  python --version
#+end_src


