#+STARTUP: showeverything
#+title: Linux Notes for Professionals

* Chapter 8: File Compression with 'tar' command

  *Common Optins*

| ~-c~, ~--create~      | Create a new archive.            |
| ~-x~, ~--extract~     | Extract files from an archive.    |
| ~-t~, ~--list~        | List the contents of an archive. |
| ~-f~, ~--file=ARCHIVE~ | Use archive file or dir ARCHIVE.  |
| ~-v~, ~--verbose~     | Verbosely list files processed.   |

  *Compression Options*

| ~-a~, ~--auto-compress~ | Use archive suffix to determine the compression program. |
| ~-j~, ~--bzip2~         | Filter the archive through bzip2.                        |
| ~-J~, ~--xz --lzma~     | Filter the archive through xz.                           |
| ~-z~, ~--gzip~          | Filter the archive through gzip.                         |

** Section 8.1: Compress a folder

   This creates a simple archive of a folder:

#+begin_src bash
  tar -cf ./my-archive.tar ./my-folder/
#+end_src

   Verbose output shows which files and directories are added to the archive, use
   the ~-v~ option:

#+begin_src bash
  tar -cvf ./my-archive.tar ./my-folder/
#+end_src

   For archiving a folder compressed 'gzip', you have to use the ~-z~ option:

#+begin_src bash
  tar -czf ./my-archive.tar.gz ./my-folder/
#+end_src

   You can instead compress the archive with 'bzip2', by using the ~-j~ option:

#+begin_src bash
  tar -cjf ./my-archive.tar.bz2 ./my-folder/
#+end_src

   Or compress with 'xz', by using the ~-J~ option:

#+begin_src bash
  tar -cJf ./my-archive.tar.xz ./my-folder/
#+end_src

** Section 8.2: Extract a folder from an archive

   There is an example for extract a folder from an archive in the current
   location:

#+begin_src bash
  tar -xf archive-name.tar
#+end_src

   If you want to extract a folder from an archive to a specfic destination:

#+begin_src bash
  tar -xf archive-name.tar -C ./directory/destination
#+end_src

** Section 8.3: List contents of an archive

   List the contents of an archive file without extracting it:

#+begin_src bash
  tar -tf archive.tar.gz
  Folder-In-Archive/
  Folder-In-Archive/file1
  Folder-In-Archive/Another-Folder/
  Folder-In-Archive/Another-Folder/file2
#+end_src

** Section 8.4: List archive content

   There is an example of listing content:

#+begin_src bash
  tar -tvf archive.tar
#+end_src

    The option ~-t~ is used for the listing. For listing the content of a
    ~tar.gz~ archive, you have to use the ~-z~ option anymore:

#+begin_src bash
  tar -tzvf archive.tar.gz
#+end_src

** Section 8.5: Compress and exclude one or multiple folder

   If you want to extract a folder, but you want to exclude one or several
   folders during the extraction, you can use the ~--exclude~ option.

#+begin_src bash
  tar -cf archive.tar ./my-folder/ --exclude="my-folder/sub1" --exclude="my-folder/sub3"
#+end_src

   With this folder tree:

#+begin_src bash
  my-folder/
     sub1/
     sub2/
     sub3/
#+end_src

   The result will be:

#+begin_src bash
  ./archive.tar
     my-folder/
     sub2/
#+end_src

** Section 8.6: Strip leading components

   To strip any number of leading components, use the --strip-components option:

#+begin_src bash
  --strip-components=NUMBER
  strip NUMBER leading components from file names on extraction
#+end_src

   For example to strip the leading folder, use:

#+begin_src bash
  tar -xf --strip-components=1 archive-name.tar
#+end_src
