#+STARTUP: showeverything
#+title: Linux Notes for Professionals

* Chapter 21: Compiling the Linux kernel

** Section 21.1: Compilation of Linux Kernel on Ubuntu

   *Warning:* be sure you have at least 15 GB of free disk space.

   Compilation in Ubuntu >=13.04

*** Option A) Use Git

    Use git if you want to stay in sync with the latest Ubuntu kernel source.
    Detailed instructions can be found in the Kernel Git Guide. The git
    repository does not include necessary control ﬁles, so you must build them
    by:

#+begin_src bash
  fakeroot debian/rules clean
#+end_src

*** Option B) Download the source archive

    Download the source archive - This is for users who want to rebuild the
    standard Ubuntu packages with additional patches. Use a follow command to
    install the build dependencies and extract the source (to the current
    directory):

    1. Install the following packages:

#+begin_src bash
  sudo apt-get build-dep linux-image-`uname -r`
#+end_src

*** Option C) Download the source package and build

    This is for users who want to modify, or play around with, the
    Ubuntu-patched kernel source.

    1. Retrieve the latest kernel source from kernel.org.

    2. Extract the archive to a directory and cd into it:

#+begin_src bash
  tar xf linux-*.tar.xz
  cd linux-*
#+end_src

    3. Build the ncurses conﬁguration interface:

#+begin_src bash
  make menuconfig
#+end_src

    4. To accept the default conﬁguration, press → to highlight < Exit > and
       then Return.

    5. Press Return again to save the conﬁguration.

    6. Use make to build the kernel:

#+begin_src bash
  make
#+end_src

       Note that you can use the -jem> ﬂag to compile ﬁles in parallel and take
       advantage of multiple cores.

   The compressed kernel image can be found at ~arch/[arch]/boot/bzImage~, where
   [arch] is equal to ~uname -a~.
