#+STARTUP: showeverything
#+title: Bash Notes for Professionals

* Chapter 19: Sourcing

** Section 19.1: Sourcing a ﬁle

   Sourcing a ﬁle is diﬀerent from execution, in that all commands are evaluated
   within the context of the current bash session - this means that any
   variables, function, or aliases deﬁned will persist throughout your session.

   Create the ﬁle you wish to source ~sourceme.sh~

#+begin_src bash
  #!/bin/bash

  export A="hello_world"
  alias sayHi="echo Hi"
  sayHello() { 
      echo Hello
  }
#+end_src

   From your session, source the ﬁle

#+begin_src bash
  $ source sourceme.sh
#+end_src

   From hencefourth, you have all the resources of the sourced ﬁle available

#+begin_src bash
  $ echo $A
  hello_world

  $ sayHi
  Hi

  $ sayHello
  Hello
#+end_src

   Note that the command . is synonymous to source, such that you can simply use

#+begin_src bash
  $ . sourceme.sh
#+end_src

** Section 19.2: Sourcing a virtual environment

   When developing several applications on one machine, it becomes useful to
   separate out dependencies into virtual environments.

   With the use of virtualenv, these environments are sourced into your shell so
   that when you run a command, it comes from that virtual environment.

   This is most commonly installed using pip.

#+begin_src bash
  pip install https://github.com/pypa/virtualenv/tarball/15.0.2
#+end_src

   Create a new environment

#+begin_src bash
  virtualenv --python=python3.5 my_env
#+end_src

   Activate the environment
