#+STARTUP: showeverything
#+title: Bash Notes for Professionals

* Chapter 57: Cut Command

| Option                         | Description                                               |
|--------------------------------+-----------------------------------------------------------|
| ~-b LIST~, ~--bytes=LIST~      | Print the bytes listed in the LIST parameter              |
| ~-c LIST~, ~--characters=LIST~ | Print characters in positions specified in LIST parameter |
| ~-f LIST~, ~--fields=LIST~     | Print fields or columns                                   |
| ~-d DELIMITER~                 | Used to separate columns or fields                        |

    In Bash, the ~cut~ command is useful for dividing a file into several smaller parts.

** Section 57.1: Show the first column of a file

   Suppose you have a file that looks like this

#+begin_src bash
  John Smith 31
  Robert Jones 27
  ...
#+end_src

   This file has 3 columns separated by spaces. To select only the first column, do the following.

#+begin_src bash
  cut -d ' ' -f1 filename
#+end_src

   Here the ~-d~ ﬂag, specifies the delimiter, or what separates the records. The ~-f~ ﬂag specifies the field or column number. This will display the following output

#+begin_src bash
  John
  Robert
  ...
#+end_src

** Section 57.2: Show columns x to y of a file

   Sometimes, it's useful to display a range of columns in a file. Suppose you have this file

#+begin_src bash
  Apple California 2017 1.00 47
  Mango Oregon 2015 2.30 chp33-debugging.org
#+end_src

   To select the first 3 columns do

#+begin_src bash
  cut -d ' ' -f 1-3 filename
#+end_src

   This will display the following output

#+begin_src bash
  Apple California 2017
  Mango Oregon 2015
#+end_src
