#+STARTUP: showeverything
#+title: Statistics and Data Analysis for Nursing Research

* Chapter 8: Correlation and Simple Regression
  
** Exercises

*** Problem A1

    Given the following circumstances, determine whether the calculated values
    of r are statistically significant:

    (a) r = .29, N = 35, a = .01, two-tailed 
    (b) r = .50, N = 15, a = .05, two-tailed 
    (c) r = .12, N = 500, a = .05, two-tailed 
    (d) r = .55, N = 12, a = .05, one-tailed 
    (e) r = .44, N = 26, a = .01, one-tailed

#+begin_src R
t_stat <- function(r, n) {
  r / sqrt(1 - r^2) * sqrt(n - 2)
}

1 - pt(t_stat(0.29, 35), df = 35 - 2)
1 - pt(t_stat(0.50, 15), df = 15 - 2)
1 - pt(t_stat(0.12, 500), df = 500 - 2)
1 - pt(t_stat(0.55, 12), df = 12 - 2)
1 - pt(t_stat(0.44, 26), df = 26 - 2)
#+end_src

#+begin_src R
> [1] 0.04552468
> [1] 0.02884942
> [1] 0.003612639
> [1] 0.03196307
> [1] 0.0122443
#+end_src

*** Problem A2

    For each correlation coefficient below, calculate what pro- portion of
    variance is shared by the two correlated variables:

    (a) r = .76 
    (b) r = .33 
    (c) r = .91 
    (d) r = .14

#+begin_src R
0.76^2
0.33^2
0.91^2
0.14^2
#+end_src

#+begin_src R
> [1] 0.5776
> [1] 0.1089
> [1] 0.8281
> [1] 0.0196
#+end_src

*** Problem A3

    For each coefficient of determination below, calculate the value of the
    correlation coefficient:

    (a) r^2 = .66 
    (b) r^2 = .13 
    (c) r^2 = .29 
    (d) r^2 = .07

#+begin_src R
sqrt(0.66)
sqrt(0.13)
sqrt(0.29)
sqrt(0.07)
#+end_src

#+begin_src R
> [1] 0.8124038
> [1] 0.3605551
> [1] 0.5385165
> [1] 0.2645751
#+end_src

*** Problem A4

    In a random sample of 100 people, the correlation between amount of daily
    exercise and weight was found to be -0.21. What would be the likely effect
    on the absolute value of the correlation coefficient under the following
    circumstances:

    (a) The sample is restricted to people who weighed under 180 pounds.

    abs(r) will likely get smaller.

    (b) The sample is restricted to people who get virtually no daily exercise
    versus those who exercise at least 30 minutes a day.

    abs(r) will likely get larger.

    (c) The mean sample weight is 150 pounds, and one person is added to the
    sample who weighs 275 pounds.

    abs(r) will likely get larger

*** Problem A5

    Suppose that a researcher regressed surgical patients’ length of stay in
    hospital (Y) on a scale of functional ability measured 24 hours after
    surgery (X). Given the following, solve for the value of the intercept
    constant and write out the full regression equation: Mean length of stay =
    6.5 days; mean score on scale = 33.0; slope = 0.10.

#+begin_src R
> 6.5 - -0.1 * 33
9.8
#+end_src
    
*** Problem A6 

    Using the regression equation calculated in response to question 5,
    compute the predicted value of Y (length of hospital stay) for patients with
    the following functional ability scores:

    (a) X = 52 
    (b) X = 68 
    (c) X = 23 
    (d) X = 10

#+begin_src R
predict_y <- function(x) {
  9.8 - 0.1 * x
}

predict_y(52)
predict_y(68)
predict_y(23)
predict_y(10)
#+end_src

#+begin_src R
> [1] 4.6
> [1] 3
> [1] 7.5
> [1] 8.8
#+end_src

*** Problem A7

    A researcher studying the relationship between maternal age and length of
    breastfeeding in a sample of 75 primiparas found a correlation of .19,
    which was not statistically significant at the .05 level. What was the
    estimated power of the statistical test? Conversely, what was the risk that
    a Type II error was committed?

#+begin_src R
> pwr::pwr.r.test(n = 75, r = 0.19, sig.level = 0.05)$power
[1] 0.3750773

> 1 - pwr::pwr.r.test(n = 75, r = 0.19, sig.level = 0.05)$power
[1] 0.6249227
#+end_src

*** Problem A8

    Assuming in question A7 that .19 is a good estimation of the population
    correlation, what sample size would be needed in a replication study to
    achieve power = .80 at alpha = .05?

#+begin_src R
> pwr::pwr.r.test(power = 0.8, r = 0.19, sig.level = 0.05)$n
[1] 214.2852
#+end_src


