#+STARTUP: showeverything
#+title: Statistics and Data Analysis for Nursing Research

* Chapter 9: Multiple Regression
  
** Exercises

*** Problem A1

    Using the regression equation for predicting graduate GPA presented in this
    chapter, compute the following for the last two students in Table 1:

    (a) the predicted value of Y; and 
    (b) the squared error term.

#+begin_src R
undergrad_gpa <- c(3.4, 3.1, 3.7, 3.2, 3.5, 2.9, 3.3, 2.9, 3.4, 3.2, 3.7, 3.0, 3.1, 3.7, 3.9, 3.5, 3.1, 2.9, 3.2, 3.6)
gre_verbal <- c(600, 510, 650, 530, 610, 540, 530, 540, 550, 700, 630, 480, 530, 580, 710, 500, 490, 560, 550, 600)
gre_quant <- c(540, 480, 710, 450, 500, 620, 510, 600, 580, 630, 700, 490, 520, 610, 660, 480, 510, 540, 590, 550)
motivation <- c(75, 70, 85, 60, 90, 60, 75, 55, 75, 65, 80, 75, 60, 65, 80, 75, 60, 55, 65, 60)
graduate_gpa <- c(3.6, 3.0, 3.9, 2.8, 3.7, 2.6, 3.4, 2.7, 3.3, 3.5, 3.6, 2.8, 3.0, 3.5, 3.8, 3.2, 2.4, 2.7, 3.1, 3.6)

data <- data.frame(
  graduate_gpa,
  undergrad_gpa,
  gre_verbal,
  gre_quant,
  motivation
)

fit <- lm(
  graduate_gpa ~ undergrad_gpa + gre_verbal + gre_quant + motivation,
  data = data
)

> predict(fit)
       1        2        3        4        5        6        7        8 
3.444361 2.945278 3.804293 2.978016 3.743894 2.694377 3.179928 2.649459 
       9       10       11       12       13       14       15       16 
3.262550 3.444001 3.690646 2.836588 2.864246 3.420692 4.099885 3.241117 
      17       18       19       20 
2.746763 2.751482 3.005102 3.397320

> summary(fit)$residuals^2
          1           2           3           4           5           6 
0.024223352 0.002994467 0.009159785 0.031689751 0.001926708 0.008906975 
          7           8           9          10          11          12 
0.048431572 0.002554350 0.001402522 0.003135857 0.008216751 0.001338646 
         13          14          15          16          17          18 
0.018429015 0.006289740 0.089930835 0.001690632 0.120244496 0.002650354 
         19          20 
0.009005561 0.041079239 
#+end_src

*** Problem A2

    Using the following information for R2, k, and N, calculate the value of the
    F statistic for testing the overall regression equation and determine
    whether the F is statistically significant at the .05 level: 

    (a) R2 = .53, k = 5, N = 120 
    (b) R2 = .53, k = 5, N = 30 
    (c) R2 = .28, k = 4, N = 64 
    (d) R2 = .14, k = 4, N = 64

#+begin_src R
f_ratio <- function(r2, k, n) {
  (r2 / k) / (
    (1 - r2) / (n - k - 1)
  )
}

> f_ratio(0.53, 5, 120)
> qf(0.95, 5, (120 - 5 - 1))
[1] 25.71064
[1] 2.293911
 
> f_ratio(0.53, 5, 30)
> qf(0.95, 5, (30 - 5 - 1))
 
[1] 5.412766
[1] 2.620654
 
> f_ratio(0.28, 4, 64)
> qf(0.95, 4, (64 - 4 - 1)) 
[1] 5.736111
[1] 2.527907
 
> f_ratio(0.14, 4, 64)
> qf(0.95, 5, (64 - 4 - 1))
[1] 2.401163
[1] 2.370977
#+end_src

*** Problem A3

    Which, if any, of the tests described in Exercise A2 would be statistically
    significant with alpha = .001?

#+begin_src R
> f_ratio(0.53, 5, 120)
> qf(0.99, 5, (120 - 5 - 1))
[1] 25.71064
[1] 3.182017

> f_ratio(0.53, 5, 30)
> qf(0.99, 5, (30 - 5 - 1))
[1] 5.412766
[1] 3.89507
 
> f_ratio(0.28, 4, 64)
> qf(0.99, 4, (64 - 4 - 1))
[1] 5.736111
[1] 3.654961
 
> f_ratio(0.14, 4, 64)
> qf(0.99, 5, (64 - 4 - 1))
[1] 2.401163
[1] 3.344654
#+end_src

*** Problem A4

    Following is a correlation matrix:

|      | VARA | VARB | VARC | DVAR |
|------+------+------+------+------|
| VARA | 1.00 |      |      |      |
| VARB | 0.62 | 1.00 |      |      |
| VARC | 0.77 | 0.68 | 1.00 |      |
| DVAR | 0.54 | 0.36 | 0.48 | 1.00 |

   (a) If DVAR were regressed on VARA, VARB, and VARC, what is the lowest
   possible value of R2?

   R2 cannot be less than the hihest bivariate correlation between Y and the Xs.

#+begin_src R
> 0.54^2
[1] 0.2916
#+end_src
   
   (b) In a stepwise regression, what would be the first predictor variable into
   the equation?

   VARA

   (c) In a stepwise regression, what would be the second predictor variable
   into the equation?

   Cannot be readily determined.

*** Problem A5

    Suppose that, using dummy codes, smokers were coded 1 and nonsmokers were
    coded 0 on SMOKSTAT, and that males were coded 1 and females were coded 0 on
    GENDER. What would be the 4 codes for the interaction term?

    Male smokers = 1 female smokers = 0, male nonsmokers = 0, female nonsmokers = 0

*** Problem A6

    Using the Internet resource recommended in this chapter (or another similar
    online calculator), find the 95% confidence limits of R2 for the following
    situations:

    (a) R2 = .22, k = 6, N = 100 
    (b) R2 = .22, k = 6, N = 200 
    (c) R2 = .22, k = 10, N = 100

#+begin_src R
> psychometric::CI.Rsq(0.22, 100, 6)
   Rsq      SErsq        LCL       UCL
1 0.22 0.06705358 0.08857739 0.3514226

> psychometric::CI.Rsq(0.22, 200, 6)
   Rsq      SErsq       LCL       UCL
1 0.22 0.04955879 0.1228666 0.3171334

> psychometric::CI.Rsq(0.22, 100, 10)
   Rsq      SErsq        LCL     UCL
1 0.22 0.06416956 0.09422998 0.34577
#+end_src

*** Problem A7

    For the following situations, estimate how large a sample would be needed
    for a multiple regression analysis to achieve standard statistical criteria,
    using Table 7.

    (a) Estimated R2 = .20, k = 6 
    (b) Estimated R2 = .13, k = 8 
    (c) Estimated R2 = .08, k = 4

#+begin_src R
pwr::pwr.f2.test(
  u = 6,
  f2 = 0.20 / (1 - 0.20),
  sig.level = 0.05,
  power = 0.80
)$v + 6 + 1

pwr::pwr.f2.test(
  u = 8,
  f2 = 0.13 / (1 - 0.13),
  sig.level = 0.05,
  power = 0.80
)$v + 8 + 1

pwr::pwr.f2.test(
  u = 4,
  f2 = 0.08 / (1 - 0.08),
  sig.level = 0.05,
  power = 0.80
)$v + 4 + 1

[1] 61.09317
[1] 108.5232
[1] 142.0806
#+end_src
